version: '3'

services:
  client:
    build: ./frontend
    ports:
      - 3000:3000
    volumes: 
      - ./frontend:/home/ubuntu/deployment/app
      - node_modules:/home/ubuntu/deployment/app/node_modules
      

  server:
    build: ./backend
    ports:
      - 3001:3000
    volumes:
      - ./backend:/home/ubuntu/deployment/backend-app
      - node_modules_b:/home/ubuntu/deployment/backend-app/node_modules


volumes: 
  node_modules:
  node_modules_b:
  data:
    
